version: "3.8"

services:
  preprocessing:
    container_name: preprocessing
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: [
        "sh",
        "-c",
        "
        python3 src/scraping/download_anexos.py &&
        python3 src/data_processing/pdf_to_csv.py &&
        python3 src/database/download_data.py
        ",
      ]
    volumes:
      - ./backend:/app
    mem_limit: 2048m
    cpus: 1

  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teste
    ports:
      - "5432:5432"
    volumes:
      - ./backend/data/csv:/csv-data
      - ./backend/src/database:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    depends_on:
      preprocessing:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d teste"]
      interval: 10s
      start_period: 15s
      timeout: 3s
      retries: 5

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=src.api.app
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_URL=postgresql://user:password@db/teste
    depends_on:
      db:
        condition: service_healthy
    command: ["flask", "run"]

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:5000
        - VITE_BASE_URL=http://localhost:8080
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db-data:
